apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: three-tier
type: Opaque
stringData:
  host:     "<RDS_ENDPOINT>"
  port:     "5432"
  dbname:   "appdb"
  username: "dbadmin"
  password: "<FROM_SECRETS_MANAGER>"